### ISSUE TITLE
error when update to 4.10.2

### ISSUE THREAD

**Issue by stepdes** [grzegorz914/homebridge-melcloud-control#245]
Got this error when update from 4.10.0 to 4.10.2:

[homebridge-melcloud-control-error.log](https://github.com/user-attachments/files/27048077/homebridge-melcloud-control-error.log)

Running post-install scripts...
npm error code MODULE_NOT_FOUND
npm error Cannot find module 'promise-retry'
npm error Require stack:
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/node_modules/pacote/lib/fetcher.js
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/node_modules/pacote/lib/index.js
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/index.js
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/index.js
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/index.js
npm error - /opt/homebridge/lib/node_modules/npm/lib/commands/rebuild.js
npm error - /opt/homebridge/lib/node_modules/npm/lib/npm.js
npm error - /opt/homebridge/lib/node_modules/npm/lib/cli/entry.js
npm error - /opt/homebridge/lib/node_modules/npm/lib/cli.js
npm error - /opt/homebridge/lib/node_modules/npm/bin/npm-cli.js
npm error A complete log of this run can be found in: /home/homebridge/.npm/_logs/2026-04-23T14_15_30_125Z-debug-0.log
Failed to rebuild.
Restoring previous version...
Restore Complete. Installation failed.

Bundled install / update could not complete. Trying regular install / update using npm.
USER: homebridge
DIR: /var/lib/homebridge
CMD: npm install --save --omit=dev homebridge-melcloud-control@4.10.2
npm error code MODULE_NOT_FOUND
npm error Cannot find module 'promise-retry'
npm error Require stack:
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/sigstore/node_modules/@sigstore/sign/dist/external/fetch.js
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/sigstore/node_modules/@sigstore/sign/dist/external/fulcio.js
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/sigstore/node_modules/@sigstore/sign/dist/signer/fulcio/ca.js
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/sigstore/node_modules/@sigstore/sign/dist/signer/fulcio/index.js
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/sigstore/node_modules/@sigstore/sign/dist/signer/index.js
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/sigstore/node_modules/@sigstore/sign/dist/index.js
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/sigstore/dist/index.js
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/pacote/lib/registry.js
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/pacote/lib/fetcher.js
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/pacote/lib/index.js
npm error - /opt/homebridge/lib/node_modules/npm/lib/commands/install.js
npm error - /opt/homebridge/lib/node_modules/npm/lib/npm.js
npm error - /opt/homebridge/lib/node_modules/npm/lib/cli/entry.js
npm error - /opt/homebridge/lib/node_modules/npm/lib/cli.js
npm error - /opt/homebridge/lib/node_modules/npm/bin/npm-cli.js
npm error A complete log of this run can be found in: /home/homebridge/.npm/_logs/2026-04-23T14_15_30_422Z-debug-0.log

Error: Operation failed with code 1.

**Comment by grzegorz914** [comment]
Not a plugin problem, check Your node and npm installation

```
Extracted to: /var/lib/homebridge/node_modules

Running post-install scripts...
npm error code MODULE_NOT_FOUND
npm error Cannot find module 'promise-retry'
npm error Require stack:
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/node_modules/pacote/lib/fetcher.js
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/node_modules/pacote/lib/index.js
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/index.js
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/index.js
npm error - /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/index.js
npm error - /opt/homebridge/lib/node_modules/npm/lib/commands/rebuild.js
npm error - /opt/homebridge/lib/node_modules/npm/lib/npm.js
npm error - /opt/homebridge/lib/node_modules/npm/lib/cli/entry.js
npm error - /opt/homebridge/lib/node_modules/npm/lib/cli.js
npm error - /opt/homebridge/lib/node_modules/npm/bin/npm-cli.js
npm error A complete log of this run can be found in: /home/homebridge/.npm/_logs/2026-04-23T14_15_30_125Z-debug-0.log
Failed to rebuild.
Restoring previous version...
Restore Complete. Installation failed.
```
